### ISSUE TITLE
Breadcrumb trail error

### ISSUE THREAD

**Issue by daphilli224** [torvista/Zen_Cart-Product_Listing_Sorter#4]
If the product category is changed using the sidebox after a product info page is viewed in another category, the product viewed still appears at the end of the breadcrumb trail for the new category. This is incorrect since the product at the end of the breadcrumb trail does not exist in the new category. This occurs in an out-of-box zencart version 1.5.7c with no other plugins or changes except Product Listing Sorter.

The problem is fixed by commenting out line 36 and uncommenting line 35 in includes/templates/YOUR_TEMPLATE/sideboxes/categories.php.

zc157c, Product Listing Sorter version 2.3 (from this site), php 7.3.29

Problem initially reported in the zen cart forum at https://www.zen-cart.com/showthread.php?228819-Breadcrumb-Issue

**Comment by torvista** [comment]
thanks

**Comment by torvista** [comment]
Change
`$content .= '<li><a class="' . $new_style . '" href="' . zen_href_link(FILENAME_DEFAULT, $box_categories_array[$i]['path']) . '&' . (zen_get_all_get_params(['cPath', 'product_listing_sorter'])) . '">';`

to

`$content .= '<li><a class="' . $new_style . '" href="' . zen_href_link(FILENAME_DEFAULT, $box_categories_array[$i]['path']) . '&' . (zen_get_all_get_params(['cPath', 'product_id'])) . '">';`

Two mistakes fixed there.
An overhauled version will be posted shortly.
